DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS comments (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(3000) NOT NULL,
    author_id BIGINT NOT NULL,
    event_id  BIGINT NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    edited    TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_event ON comments(event_id);