server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always