server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /users/**
        - id: category-service-route
          uri: lb://category-service
          predicates:
            - Path=/categories/**, /admin/categories/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
      show-details: always