spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: main-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
        retry:
          max-attempts: 60
          initial-interval: 2000
          multiplier: 1.1
      retry:
        useRandomPolicy: true
        max-interval: 6000
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/